const games = [
	{
		id: crypto.randomUUID(),
		name: 'The Witcher 3: Wild Hunt',
		price: 40,
		category: 'RPG',
		platform: 'PC',
		image_url: 'witcher3.avif',
	},
	{
		id: crypto.randomUUID(),
		name: 'Red Dead Redemption 2',
		price: 60,
		category: 'Action-Adventure',
		platform: 'PS4',
		image_url: 'rdr2.jpeg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Overwatch',
		price: 30,
		category: 'Shooter',
		platform: 'PC',
		image_url: 'overwatch.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Minecraft',
		price: 20,
		category: 'Sandbox',
		platform: 'PC',
		image_url: 'minecraft.webp',
	},
	{
		id: crypto.randomUUID(),
		name: 'Fortnite',
		price: 0,
		category: 'Battle Royale',
		platform: 'PC',
		image_url: 'fortnite.avif',
	},
	{
		id: crypto.randomUUID(),
		name: 'The Elder Scrolls V: Skyrim',
		price: 40,
		category: 'RPG',
		platform: 'PC',
		image_url: 'elders.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Cyberpunk 2077',
		price: 60,
		category: 'RPG',
		platform: 'PC',
		image_url: 'cyberpunk.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Grand Theft Auto V',
		price: 30,
		category: 'Action-Adventure',
		platform: 'PC',
		image_url: 'gta5.webp',
	},
	{
		id: crypto.randomUUID(),
		name: 'League of Legends',
		price: 0,
		category: 'MOBA',
		platform: 'PC',
		image_url: 'lol.webp',
	},
	{
		id: crypto.randomUUID(),
		name: 'Call of Duty: Modern Warfare',
		price: 60,
		category: 'Shooter',
		platform: 'PS4',
		image_url: 'cod.avif',
	},
	{
		id: crypto.randomUUID(),
		name: 'Stardew Valley',
		price: 15,
		category: 'Simulation',
		platform: 'PC',
		image_url: 'stardeew.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Among Us',
		price: 5,
		category: 'Party',
		platform: 'PC',
		image_url: 'amongus.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Animal Crossing: New Horizons',
		price: 60,
		category: 'Simulation',
		platform: 'Switch',
		image_url: 'animalcrossing.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'DOOM Eternal',
		price: 60,
		category: 'Shooter',
		platform: 'PC',
		image_url: 'doom.jpg',
	},
	{
		id: crypto.randomUUID(),
		name: 'Hades',
		price: 25,
		category: 'Roguelike',
		platform: 'PC',
		image_url: 'hades.avif',
	},
]

module.exports = {
	games,
}
